clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "





python3 /home/ubuntu/Desktop/prox2/BTC.py &
python3 /home/ubuntu/Desktop/prox2/ETH.py &
python3 /home/ubuntu/Desktop/prox2/BNB.py &
python3 /home/ubuntu/Desktop/prox2/XRP.py &
python3 /home/ubuntu/Desktop/prox2/ADA.py &
python3 /home/ubuntu/Desktop/prox2/SOL.py &
python3 /home/ubuntu/Desktop/prox2/DOGE.py &
python3 /home/ubuntu/Desktop/prox2/MATIC.py &
python3 /home/ubuntu/Desktop/prox2/DOT.py &
python3 /home/ubuntu/Desktop/prox2/DAI.py &
python3 /home/ubuntu/Desktop/prox2/SHIB.py &
python3 /home/ubuntu/Desktop/prox2/TRX.py &
python3 /home/ubuntu/Desktop/prox2/AVAX.py &
python3 /home/ubuntu/Desktop/prox2/UNI.py &
python3 /home/ubuntu/Desktop/prox2/WBTC.py &
python3 /home/ubuntu/Desktop/prox2/LEO.py &
python3 /home/ubuntu/Desktop/prox2/LTC.py &
python3 /home/ubuntu/Desktop/prox2/ATOM.py &
python3 /home/ubuntu/Desktop/prox2/LINK.py &
python3 /home/ubuntu/Desktop/prox2/ETC.py &
python3 /home/ubuntu/Desktop/prox2/XLM.py &
python3 /home/ubuntu/Desktop/prox2/FTT.py &
python3 /home/ubuntu/Desktop/prox2/NEAR.py &
python3 /home/ubuntu/Desktop/prox2/CRO.py &
python3 /home/ubuntu/Desktop/prox2/XMR.py &
python3 /home/ubuntu/Desktop/prox2/ALGO.py &
python3 /home/ubuntu/Desktop/prox2/BCH.py &
python3 /home/ubuntu/Desktop/prox2/LUNC.py &
python3 /home/ubuntu/Desktop/prox2/QNT.py &
python3 /home/ubuntu/Desktop/prox2/FLOW.py &
python3 /home/ubuntu/Desktop/prox2/VET.py &
python3 /home/ubuntu/Desktop/prox2/TON.py &
python3 /home/ubuntu/Desktop/prox2/APE.py &
python3 /home/ubuntu/Desktop/prox2/FIL.py &
python3 /home/ubuntu/Desktop/prox2/ICP.py &
python3 /home/ubuntu/Desktop/prox2/HBAR.py &
python3 /home/ubuntu/Desktop/prox2/EGLD.py &
python3 /home/ubuntu/Desktop/prox2/XTZ.py &
python3 /home/ubuntu/Desktop/prox2/MANA.py &
python3 /home/ubuntu/Desktop/prox2/SAND.py &
python3 /home/ubuntu/Desktop/prox2/CHZ.py &
python3 /home/ubuntu/Desktop/prox2/EOS.py &
python3 /home/ubuntu/Desktop/prox2/AAVE.py &
python3 /home/ubuntu/Desktop/prox2/THETA.py &
python3 /home/ubuntu/Desktop/prox2/AXS.py &
python3 /home/ubuntu/Desktop/prox2/USDP.py &
python3 /home/ubuntu/Desktop/prox2/OKB.py &
python3 /home/ubuntu/Desktop/prox2/BSV.py &
python3 /home/ubuntu/Desktop/prox2/TUSD.py &
python3 /home/ubuntu/Desktop/prox2/MKR.py &
python3 /home/ubuntu/Desktop/prox2/KCS.py &
python3 /home/ubuntu/Desktop/prox2/ZEC.py &
python3 /home/ubuntu/Desktop/prox2/USDD.py &
python3 /home/ubuntu/Desktop/prox2/HT.py &
python3 /home/ubuntu/Desktop/prox2/XEC.py &
python3 /home/ubuntu/Desktop/prox2/MIOTA.py &
python3 /home/ubuntu/Desktop/prox2/BTT.py &
python3 /home/ubuntu/Desktop/prox2/USDN.py &
python3 /home/ubuntu/Desktop/prox2/CAKE.py &
python3 /home/ubuntu/Desktop/prox2/GRT.py &
python3 /home/ubuntu/Desktop/prox2/NEO.py &
python3 /home/ubuntu/Desktop/prox2/HNT.py &
python3 /home/ubuntu/Desktop/prox2/KLAY.py &
python3 /home/ubuntu/Desktop/prox2/FTM.py &
python3 /home/ubuntu/Desktop/prox2/PAXG.py &
python3 /home/ubuntu/Desktop/prox2/SNX.py &
python3 /home/ubuntu/Desktop/prox2/RUNE.py &
python3 /home/ubuntu/Desktop/prox2/NEXO.py &
python3 /home/ubuntu/Desktop/prox2/GT.py &
python3 /home/ubuntu/Desktop/prox2/DASH.py &
python3 /home/ubuntu/Desktop/prox2/CRV.py &
python3 /home/ubuntu/Desktop/prox2/BAT.py &
python3 /home/ubuntu/Desktop/prox2/ENJ.py &
python3 /home/ubuntu/Desktop/prox2/LDO.py &
python3 /home/ubuntu/Desktop/prox2/STX.py &
python3 /home/ubuntu/Desktop/prox2/KAVA.py &
python3 /home/ubuntu/Desktop/prox2/COMP.py &
python3 /home/ubuntu/Desktop/prox2/ZIL.py &
python3 /home/ubuntu/Desktop/prox2/FEI.py &
python3 /home/ubuntu/Desktop/prox2/RVN.py &
python3 /home/ubuntu/Desktop/prox2/MINA.py &
python3 /home/ubuntu/Desktop/prox2/WAVES.py &
python3 /home/ubuntu/Desktop/prox2/XDC.py &
python3 /home/ubuntu/Desktop/prox2/USDTC.py &
python3 /home/ubuntu/Desktop/prox2/GMT.py &
python3 /home/ubuntu/Desktop/prox2/TWT.py &
python3 /home/ubuntu/Desktop/prox2/LRC.py &
python3 /home/ubuntu/Desktop/prox2/DCR.py &
python3 /home/ubuntu/Desktop/prox2/CVX.py &
python3 /home/ubuntu/Desktop/prox2/CSPR.py &
python3 /home/ubuntu/Desktop/prox2/XEM.py &
python3 /home/ubuntu/Desktop/prox2/KSM.py &
python3 /home/ubuntu/Desktop/prox2/CELO.py &
python3 /home/ubuntu/Desktop/prox2/BTG.py &
python3 /home/ubuntu/Desktop/prox2/ENS.py &
python3 /home/ubuntu/Desktop/prox2/1INCH.py &
python3 /home/ubuntu/Desktop/prox2/HOT.py &
python3 /home/ubuntu/Desktop/prox2/LUNA.py &
python3 /home/ubuntu/Desktop/prox2/RSR.py &
python3 /home/ubuntu/Desktop/prox2/BNX.py &
python3 /home/ubuntu/Desktop/prox2/GUSD.py &
python3 /home/ubuntu/Desktop/prox2/ROSE.py &
python3 /home/ubuntu/Desktop/prox2/YFI.py &
python3 /home/ubuntu/Desktop/prox2/QTUM.py &
python3 /home/ubuntu/Desktop/prox2/AR.py &
python3 /home/ubuntu/Desktop/prox2/ANKR.py &
python3 /home/ubuntu/Desktop/prox2/GNO.py &
python3 /home/ubuntu/Desktop/prox2/GALA.py &
python3 /home/ubuntu/Desktop/prox2/TFUEL.py &
python3 /home/ubuntu/Desktop/prox2/KDA.py &
python3 /home/ubuntu/Desktop/prox2/IOTX.py &
python3 /home/ubuntu/Desktop/prox2/GLM.py &
python3 /home/ubuntu/Desktop/prox2/BTRST.py &
python3 /home/ubuntu/Desktop/prox2/JST.py &
python3 /home/ubuntu/Desktop/prox2/CEL.py &
python3 /home/ubuntu/Desktop/prox2/POLY.py &
python3 /home/ubuntu/Desktop/prox2/ONE.py &
python3 /home/ubuntu/Desktop/prox2/HIVE.py &
python3 /home/ubuntu/Desktop/prox2/OMG.py &
python3 /home/ubuntu/Desktop/prox2/LPT.py &
python3 /home/ubuntu/Desktop/prox2/ZRX.py &
python3 /home/ubuntu/Desktop/prox2/BAL.py &
python3 /home/ubuntu/Desktop/prox2/FLUX.py &
python3 /home/ubuntu/Desktop/prox2/IOST.py &
python3 /home/ubuntu/Desktop/prox2/ICX.py &
python3 /home/ubuntu/Desktop/prox2/BORA.py &
python3 /home/ubuntu/Desktop/prox2/AMP.py &
python3 /home/ubuntu/Desktop/prox2/XYM.py &
python3 /home/ubuntu/Desktop/prox2/SRM.py &
python3 /home/ubuntu/Desktop/prox2/KNC.py &
python3 /home/ubuntu/Desktop/prox2/ONT.py &
python3 /home/ubuntu/Desktop/prox2/OP.py &
python3 /home/ubuntu/Desktop/prox2/GLMR.py &
python3 /home/ubuntu/Desktop/prox2/CHSB.py &
python3 /home/ubuntu/Desktop/prox2/STORJ.py &
python3 /home/ubuntu/Desktop/prox2/WAXP.py &
python3 /home/ubuntu/Desktop/prox2/SC.py &
python3 /home/ubuntu/Desktop/prox2/WOO.py &
python3 /home/ubuntu/Desktop/prox2/ZEN.py &
python3 /home/ubuntu/Desktop/prox2/XCH.py &
python3 /home/ubuntu/Desktop/prox2/SXP.py &
python3 /home/ubuntu/Desktop/prox2/SUSHI.py &
python3 /home/ubuntu/Desktop/prox2/IMX.py &
python3 /home/ubuntu/Desktop/prox2/MXC.py &
python3 /home/ubuntu/Desktop/prox2/AUDIO.py &
python3 /home/ubuntu/Desktop/prox2/NFT.py &
python3 /home/ubuntu/Desktop/prox2/UMA.py &
python3 /home/ubuntu/Desktop/prox2/PLA.py &
python3 /home/ubuntu/Desktop/prox2/SKL.py &
python3 /home/ubuntu/Desktop/prox2/ABBC.py &
python3 /home/ubuntu/Desktop/prox2/SCRT.py &
python3 /home/ubuntu/Desktop/prox2/SLP.py &
python3 /home/ubuntu/Desktop/prox2/DGB.py &
python3 /home/ubuntu/Desktop/prox2/ELON.py &
python3 /home/ubuntu/Desktop/prox2/INJ.py &
python3 /home/ubuntu/Desktop/prox2/VGX.py &
python3 /home/ubuntu/Desktop/prox2/CKB.py &
python3 /home/ubuntu/Desktop/prox2/CVC.py &
python3 /home/ubuntu/Desktop/prox2/LSK.py &
python3 /home/ubuntu/Desktop/prox2/VLX.py &
python3 /home/ubuntu/Desktop/prox2/PUNDIX.py &
python3 /home/ubuntu/Desktop/prox2/COTI.py &
python3 /home/ubuntu/Desktop/prox2/KEEP.py &
python3 /home/ubuntu/Desktop/prox2/DAO.py &
python3 /home/ubuntu/Desktop/prox2/REN.py &
python3 /home/ubuntu/Desktop/prox2/MED.py &
python3 /home/ubuntu/Desktop/prox2/RNDR.py &
python3 /home/ubuntu/Desktop/prox2/CEEK.py &
python3 /home/ubuntu/Desktop/prox2/REEF.py &
python3 /home/ubuntu/Desktop/prox2/EWT.py &
python3 /home/ubuntu/Desktop/prox2/PEOPLE.py &
python3 /home/ubuntu/Desktop/prox2/BTCST.py &
python3 /home/ubuntu/Desktop/prox2/WIN.py &
python3 /home/ubuntu/Desktop/prox2/NU.py &
python3 /home/ubuntu/Desktop/prox2/CELR.py &
python3 /home/ubuntu/Desktop/prox2/SYS.py &
python3 /home/ubuntu/Desktop/prox2/ONG.py &
python3 /home/ubuntu/Desktop/prox2/XNO.py &
python3 /home/ubuntu/Desktop/prox2/REQ.py &
python3 /home/ubuntu/Desktop/prox2/DAG.py &
python3 /home/ubuntu/Desktop/prox2/ORBS.py &
python3 /home/ubuntu/Desktop/prox2/SPELL.py &
python3 /home/ubuntu/Desktop/prox2/RLC.py &
python3 /home/ubuntu/Desktop/prox2/OCEAN.py &
python3 /home/ubuntu/Desktop/prox2/API3.py &
python3 /home/ubuntu/Desktop/prox2/SNT.py &
python3 /home/ubuntu/Desktop/prox2/TRIBE.py &
python3 /home/ubuntu/Desktop/prox2/ARDR.py &
python3 /home/ubuntu/Desktop/prox2/PYR.py &
python3 /home/ubuntu/Desktop/prox2/FX.py &
python3 /home/ubuntu/Desktop/prox2/UOS.py &
python3 /home/ubuntu/Desktop/prox2/POWER.py &
python3 /home/ubuntu/Desktop/prox2/ACA.py &
python3 /home/ubuntu/Desktop/prox2/PROM.py &
python3 /home/ubuntu/Desktop/prox2/DENT.py &
python3 /home/ubuntu/Desktop/prox2/CHR.py &
python3 /home/ubuntu/Desktop/prox2/MX.py &
python3 /home/ubuntu/Desktop/prox2/%launcher%


